config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "customers#index"

  # Routing the alphabetized and missing email customers.
  get "/customers/alphabetized", to: "customers#alphabetized"
  get "/customers/missing_email", to: "customers#missing_email"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_one_attached :avatar

  validates :full_name, :phone_number, presence: true
  validates :full_name, :email_address, length: { maximum: 75 }

  # Permits active_admin to filter and search with these attributes.
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email_address", "full_name", "id", "id_value", "notes", "phone_number", "updated_at"]
  end


  def self.ransackable_associations(auth_object = nil)
    ["avatar_attachment", "avatar_blob"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  # Returns all customers in alphabetical order.
  def alphabetized
    @customers = Customer.order(:full_name)
  end

  # Returns only the customers who are missing emails.
  def missing_email
    @customers = Customer.where(email_address: [nil, ""])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<div class="box is-radiusless column is-one-fifth is-full-mobile  mx-3">
  <h2 class="has-text-weight-bold is-size-5"><%= customer.full_name %></h2>

  <% if customer.avatar.attached? %>
    <div class="mx-2">
      <%= image_tag(customer.avatar) %>
    </div>
  <% end %>

  <p class="mt-3 is-size-7"><%= customer.phone_number %></p>
  <p class="mt-5 is-size-7"><%= customer.email_address %></p>
</div>

app/views/customers/_links.html.erb
<div class="is-flex is-justify-content-center">
  <%= link_to "Home", root_path, class:"mx-3" %>
  <%= link_to "Alphabetized", customers_alphabetized_path, class:"mx-3" %>
  <%= link_to "Missing Emails", customers_missing_email_path, class:"mx-3" %>
</div>

app/views/customers/alphabetized.html.erb
<div class="is-flex is-flex-wrap-wrap is-justify-content-space-around">
  <h1 class="pl-5 has-text-weight-bold">Alphabetized Customers</h1>

  <div class="columns is-multiline is-centered px-5">
    <% @customers.each do |customer| %>
      <%= render partial: "customer", locals: {customer: customer} %>
    <% end %>
  </div>
  <%= render "links" %>
</div>

app/views/customers/index.html.erb
<div class="is-flex is-flex-wrap-wrap is-justify-content-space-around">
  <h1 class="pl-5 has-text-weight-bold">All Customers</h1>

  <div class="columns is-multiline is-centered px-5">
    <% @customers.each do |customer| %>
      <%= render partial: "customer", locals: {customer: customer} %>
    <% end %>
  </div>
  <%= render "links" %>
</div>

app/views/customers/missing_email.html.erb
<div class="is-flex is-flex-wrap-wrap is-justify-content-space-around">
  <h1 class="pl-5 has-text-weight-bold">Customers Missing an Email</h1>

  <div class="columns is-multiline is-centered px-5">
    <% @customers.each do |customer| %>
      <%= render partial: "customer", locals: {customer: customer} %>
    <% end %>
  </div>
  <%= render "links" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Challenge6Webd3011MSobering</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>